### ISSUE TITLE
imagine@1.1.1: hash check failed

### ISSUE THREAD

**Issue by kwanggoo** [dodorz/scoop#13]
App:         dodorz/imagine
URL:         http://www.nyam.pe.kr/dev/imagine/download/x64/Imagine_1.1.1_x64_Unicode.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    e81a63d5ca938260cde93f1ee81f2cff1e604641f52b55d317416d424877105e
Actual:      985f05102a8519bd75bbaa89fb697037d0c0889ed9bd8431f64eb309e7e43b3f

**Comment by dodorz** [comment]
Thank you ! I've fix it. Please `scoop update` and try again.
