### ISSUE TITLE
Can't shim 'TeraCopy.exe': File doesn't exist.

### ISSUE THREAD

**Issue by kwanggoo** [dodorz/scoop#14]
Installing 'innounp' (0.50) [64bit]
innounp050.rar (138.3 KB) [===========================================] 100%
Checking hash of innounp050.rar ... ok.
Extracting innounp050.rar ... done.
Linking ~\scoop\apps\innounp\current => ~\scoop\apps\innounp\0.50
Creating shim for 'innounp'.
'innounp' (0.50) was installed successfully!
Installing 'teracopy' (3.8.2) [64bit]
teracopy.exe (7.1 MB) [===============================================] 100%
Checking hash of teracopy.exe ... ok.
Extracting teracopy.exe#tera.exe ... done.
Linking ~\scoop\apps\teracopy\current => ~\scoop\apps\teracopy\3.8.2
Creating shim for 'TeraCopy'.
Can't shim 'TeraCopy.exe': File doesn't exist.

**Comment by dodorz** [comment]
Thank you ! I've fix it. Please `scoop update` and try again.
