### ISSUE TITLE
YoudaoDict@8.9.8.0: hash check failed

### ISSUE THREAD

**Issue by whisper540** [dodorz/scoop#16]
Download: (OK):download completed.
Checking hash of YoudaoDict.exe ... ERROR Hash check failed!
App:         dodorz/YoudaoDict
URL:         http://cidian.youdao.com/download/YoudaoDict.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    b3f141e68e2e0e5fb3167d869846afe01571561483130465e4ddeb8bdae95d47
Actual:      76223698e710299a150f77e92fa6e7f57de8da0d96d82189e675d77759707df4

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/dodorz/scoop/issues/new?title=YoudaoDict%408.9.8.0%3a+hash+check+failed

**Comment by dodorz** [comment]
Thank you. I have fix it. You mai try it again.
