### ISSUE TITLE
justmd@1.2.1: Decompress Error

### ISSUE THREAD

**Issue by visualwind** [dodorz/scoop#19]
Could not find 'justmd-win32-x64-v1.2.1.7z in C:\Scoop\apps\justmd\1.2.1'! (error 16)

**Comment by visualwind** [comment]
scoop install justmd
Installing 'justmd' (1.2.1) [64bit] [dodorz]
WARN  By installing you accept following license: MIT (https://spdx.org/licenses/MIT.html)
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 951fb1|OK  |    11MiB/s|C:/Scoop/cache/justmd#1.2.1#https_github.com_x1y9_justmd_releases_download_v1.2.1_justmd-win32-x64-v1.2.1.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of justmd-win32-x64-v1.2.1.7z ... ok.
Extracting justmd-win32-x64-v1.2.1.7z ... ERROR Could not find 'justmd-win32-x64-v1.2.1.7z in C:\Scoop\apps\justmd\1.2.1'! (error 16)

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/dodorz/scoop/issues/new?title=justmd%401.2.1%3a+Decompress+Error&body=Could+not+find+%27justmd-win32-x64-v1.2.1.7z+in+C%3a%5cScoop%5capps%5cjustmd%5c1.2.1%27!+(error+16)

**Comment by dodorz** [comment]
Thank you! I've fix it. Please update & try again.
