### ISSUE TITLE
dodorz bucket doesnt exist anymore?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [dodorz/scoop#3]
I used to have dodorz bucket in me scoop, now it doesn't exist anymore? But it's there.... 
![image](https://user-images.githubusercontent.com/3938423/111005946-21c2b280-838c-11eb-9c0e-dd8b6d0fd1fb.png)

**Comment by jku1995** [comment]
The original repository has been deleted, please redirect to the current repository.

**Comment by Unrepentant-Atheist** [comment]
Ehh??? How do?

**Comment by Unrepentant-Atheist** [comment]
Still having this issue. What do I do??

**Comment by dodorz** [comment]
Please try remove the bucket and add it again.
`scoop bucket remove dodorz`
`scoop bucket add dodorz https://github.com/dodo/scoop.git`
Is it helpful?
