### ISSUE TITLE
nirlauncher@1.23.54: Shim creation fail

### ISSUE THREAD

**Issue by visualwind** [dodorz/scoop#36]
`Download: (OK):download completed.
Checking hash of nirsoft_package_enc_1.23.54.zip ... ok.
Running pre-install script...
Linking C:\Scoop\apps\nirlauncher\current => C:\Scoop\apps\nirlauncher\1.23.54
Creating shim for 'Nirlauncher'.
Creating shim for 'AdvancedRun'.
Creating shim for 'AllThreadsView'.
Creating shim for 'AlternateStreamView'.
Creating shim for 'AltStreamDump'.
Creating shim for 'AppAudioConfig'.
Creating shim for 'AppCompatibilityView'.
Creating shim for 'AppCrashView'.
Creating shim for 'AppNetworkCounter'.
Creating shim for 'AppReadWriteCounter'.
Creating shim for 'awatch'.
Creating shim for 'axhelper'.
Creating shim for 'BatteryInfoView'.
Creating shim for 'BlueScreenView'.
Creating shim for 'BluetoothCL'.
Creating shim for 'BluetoothLogView'.
Creating shim for 'BluetoothView'.
Creating shim for 'BrowserAddonsView'.
Creating shim for 'BrowsingHistoryView'.
Creating shim for 'BulkFileChanger'.
Creating shim for 'BulletsPassView'.
Creating shim for 'ChromeCacheView'.
Creating shim for 'ChromeCookiesView'.
Creating shim for 'ChromeHistoryView'.
Creating shim for 'ChromePass'.
Creating shim for 'CleanAfterMe'.
ERROR Cannot shim 'NirSoft/CleanAfterMe.exe': File does not exist

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/dodorz/scoop/issues/new?title=nirlauncher%401.23.54%3a+Shim+creation+fail&body=Cannot+shim+%27NirSoft%2fCleanAfterMe.exe%27%3a+File+does+not+exist
ERROR This application failed to install: nirlauncher

**Comment by tan-wei** [comment]
Met the same issue. Seems reporting virus by Windows.

**Comment by dodorz** [comment]
Thank you. It's been fixed. Please update and try again.
