### ISSUE TITLE
CoolPDFReader@3.2.1.322: hash check failed

### ISSUE THREAD

**Issue by Jambo15** [dodorz/scoop#42]
Checking hash of CoolPDFReader.exe ... ERROR Hash check failed!
App:         dodorz/CoolPDFReader
URL:         https://www.pdf2exe.com/CoolPDFReader.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    ddc0dddfb21a64cc77be6fe6ca56253bdba51d09f458087c1defef8de17717ad
Actual:      34071c688ff669cd87d5a69e421559fc94b88c125d31f94adfd5f5cdec752b31

**Comment by dodorz** [comment]
Thank you. I've fix it. Please `scoop update` and try again.
