### ISSUE TITLE
WARN  Error parsing JSON at D:\dkal\environments\scoop\scoop_custom\buckets\dodorz\duf.json.

### ISSUE THREAD

**Issue by whisper540** [dodorz/scoop#53]
WARN  Error parsing JSON at D:\dkal\environments\scoop\scoop_custom\buckets\dodorz\duf.json.

**Comment by standin000** [comment]
same issue, fix by this patch
[duf.zip](https://github.com/dodorz/scoop/files/9449309/duf.zip)

**Comment by dodorz** [comment]
Thanks. I've update to dufs. Please `scoop update` & try again.

**Comment by DrVektor** [comment]
> same issue, fix by this patch [duf.zip](https://github.com/dodorz/scoop/files/9449309/duf.zip)

How can i patch this?

**Comment by standin000** [comment]
> > same issue, fix by this patch [duf.zip](https://github.com/dodorz/scoop/files/9449309/duf.zip)
> 
> How can i patch this?

dodorz have updated, you only need run scoop update

**Comment by DrVektor** [comment]
_WARN  Error parsing JSON at C:\ProgramData\Scoop\buckets\extras\bucket\mcomix.json._ I'm sorry, that was my problem. The file at the end is different, how do I fix it? It always comes up when I search. For example, when I type "scoop search telegram", this comes up.

**Comment by synthercat** [comment]
I got this too

**Comment by DrVektor** [comment]
> I got this too

Do you know how to fix this?

**Comment by ddjoker** [comment]
> > I got this too
> 
> Do you know how to fix this?

delete ','  ....


https://github.com/ScoopInstaller/Extras/pull/12216/commits/10dfae7ba0f26b3f05cfb7ce76a18ad17b2eb633
