### ISSUE TITLE
chocolatey@0.10.15: Hash check failed

### ISSUE THREAD

**Issue by RavenMacDaddy** [dodorz/scoop#6]
Hash check failed!
App:         dodorz/chocolatey
URL:         https://chocolatey.org/install.ps1
First bytes: 60 35 13 10 32 32 32 32
Expected:    75c7b602c9d7655bb25f3fb96377bc866bca22150cb53d1e6d5edcb3f286a067
Actual:      9ec3d109d19721005a216b37d828c8f77e64fbf99fa5e9e50ed888b8c44fd6e3

**Comment by dodorz** [comment]
Thank you. I have fix it. Please try again.
