### ISSUE TITLE
Error parsing JSON at C:\Portable\scoop\buckets\dodorz\UltraSearch.json

### ISSUE THREAD

**Issue by reddevil7nine** [dodorz/scoop#64]
Missing closing brace for `autoupdate.architecture.64bit` on line 27.

**Comment by dong-lufei** [comment]
https://github.com/dodorz/scoop/blob/master/TODO/Citrio.json
https://github.com/dodorz/scoop/blob/master/UltraSearch.json

The content of these 2 files is wrong  https://github.com/ScoopInstaller/Scoop/issues/5339

**Comment by dodorz** [comment]
Thank you. I've fix it. Please `scoop update` and try again.
