### ISSUE TITLE
eudic@2022-08-15: Hash check failed

### ISSUE THREAD

**Issue by uJZk** [dodorz/scoop#69]
Hash check failed!
App:         dodorz/eudic
URL:         https://www.eudic.net/download/eudic_win.zip?v=2022-08-15
First bytes: 80 75 3 4 20 0 0 0
Expected:    9c8f700f3e9cca06b278e584dc2030f38305c97b61ade4a4902cec0b53e82dd5
Actual:      23d4895c78e1d34be4d104d7c7ee2bda00e2a7662cbaa77d025a1fc7553874b5

**Comment by dodorz** [comment]
Thank you. I've fix it. Please `scoop update` and try again.
