### ISSUE TITLE
WARN Error parsing JSON at C:\ProgramData\Scoop\buckets\extras\bucket\mcomix.json.

### ISSUE THREAD

**Issue by DrVektor** [dodorz/scoop#77]
PS C:\Windows\system32> scoop search inkscape
WARN  Error parsing JSON at C:\ProgramData\Scoop\buckets\extras\bucket\mcomix.json.
Results from local buckets...
 
This example. I am having this error when i search a program.

**Comment by dodorz** [comment]
It's something wrong with extras repo. Please open issue on https://github.com/ScoopInstaller/Extras
