### ISSUE TITLE
WARN  Error parsing JSON at C:\ProgramData\Scoop\buckets\extras\bucket\teraterm.json.

### ISSUE THREAD

**Issue by DrVektor** [dodorz/scoop#78]
scoop search krita
WARN  Error parsing JSON at C:\ProgramData\Scoop\buckets\extras\bucket\teraterm.json.
Results from local buckets...

Name  Version Source Binaries
----  ------- ------ --------
krita 5.2.1   extras

**Comment by dodorz** [comment]
It's something wrong with extras repo. Please open issue on https://github.com/ScoopInstaller/Extras
