### ISSUE TITLE
wechat@3.9.10: hash check failed

### ISSUE THREAD

**Issue by ddlee-cn** [dodorz/scoop#83]
Checking hash of WeChatSetup.exe ... ERROR Hash check failed!
App:         scpd/wechat
URL:         https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    9602acb85408ee48ee689468f63565496dfb12f1fe21ad674aa423029e38856c
Actual:      bd230520ab8debf42c282f067c55583b90f3ca11d5b929a99aeb3af51f9d23ea

**Comment by dodorz** [comment]
Thank you. I've fix it. Please `scoop update` and try it again.
