### ISSUE TITLE
qqmusic@18.07.0: hash check failed

### ISSUE THREAD

**Issue by ZhangZizhi1005** [dodorz/scoop#9]
Installing 'qqmusic' (18.07.0) [64bit]
Loading QQMusic_YQQWinPCDL.exe from cache
Checking hash of QQMusic_YQQWinPCDL.exe ... ERROR Hash check failed!
App:         dodorz/qqmusic
URL:         https://dldir1.qq.com/music/clntupate/QQMusic_YQQWinPCDL.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    d0ad6bb8295ddf27b8be0cc07c3f2c0a8e7de79c629a03401e4609c4e81544e2
Actual:      7f443698a9278dd74bcaa899a347ff4eb8521583a3575dd9b7b689f0d598de38

**Comment by dodorz** [comment]
Thanks. I've fix it. Please update & try again.
